CREATE TABLE IF NOT EXISTS APPLICATION (
    APPLICATION_ID      NUMERIC(15, 0) PRIMARY KEY,
    CREDIT_AMOUNT       NUMERIC(15, 2),
    CREDIT_RATE         NUMERIC(5, 2),
    CREDIT_TERM         NUMERIC(5, 0)
    );


CREATE TABLE IF NOT EXISTS CLIENT (
    APPLICATION_ID      NUMERIC(15, 0) REFERENCES APPLICATION(APPLICATION_ID),
    CLIENT_ID           NUMERIC(15, 0) UNIQUE,
    FIRSTNAME           VARCHAR(255),
    SURNAME             VARCHAR(255),
    LASTNAME            VARCHAR(255),
    BIRTHDATE           DATE,
    BIRTHPLACE          VARCHAR(255),
    PRIMARY KEY(APPLICATION_ID, CLIENT_ID)
);



CREATE TABLE IF NOT EXISTS ADDRESS (
    APPLICATION_ID      NUMERIC(15, 0) REFERENCES APPLICATION(APPLICATION_ID),
    CLIENT_ID           NUMERIC(15, 0) REFERENCES CLIENT(CLIENT_ID),
    ADDRESS_ID          NUMERIC(15, 0),
    COUNTRY             VARCHAR(255),
    CITY                VARCHAR(255),
    STREET              VARCHAR(255),
    HOUSE               VARCHAR(255),
    BUILDING            VARCHAR(255),
    FLAT                VARCHAR(255),
    PRIMARY KEY (APPLICATION_ID, CLIENT_ID, ADDRESS_ID)
    );


CREATE TABLE IF NOT EXISTS INCOME (
    APPLICATION_ID      NUMERIC(15, 0) REFERENCES APPLICATION(APPLICATION_ID),
    CLIENT_ID           NUMERIC(15, 0) REFERENCES CLIENT(CLIENT_ID),
    INCOME_ID           NUMERIC(15, 0),
    MONTH               DATE,
    AMOUNT              NUMERIC(15, 2),
    PRIMARY KEY (APPLICATION_ID, CLIENT_ID, INCOME_ID)
    );

CREATE SEQUENCE IF NOT EXISTS INCOME_SEQUENCE INCREMENT BY 1 MINVALUE 1 OWNED BY INCOME.INCOME_ID;

CREATE SEQUENCE IF NOT EXISTS INCOME_SEQUENCE INCREMENT BY 1 MINVALUE 1000 OWNED BY ADRESS.ADDRESS_ID;