version: '3.9'
services:
  activemq:
    image: rmohr/activemq:5.15.9-alpine
    restart: always
    ports:
      - "8161:8161"
    container_name: activemq

  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: "task-db"
      POSTGRES_USER: "glowbyte"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5433"


  app:
    image: app
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - spring.activemq.broker-url=tcp://activemq:8161
    depends_on:
      - activemq
      - postgres