version: '3.9'
services:
  activemq:
    image: rmohr/activemq:5.15.9-alpine
    restart: always
    ports:
      - "61616:61616"
    container_name: activemq

  postgres:
    build:
      context: /database
    environment:
      POSTGRES_DB: "glowbyte_db"
      POSTGRES_USER: "glowbyte"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
    container_name: postgres